services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-engine-example
    volumes:
      - ../:/var/www/html
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - search-engine-example-network

  nginx:
    image: nginx:stable-alpine
    container_name: search-engine-example-nginx
    volumes:
      - ../:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always
    networks:
      - search-engine-example-network

  mysql:
    image: mysql:8.0
    container_name: search-engine-example-db
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    restart: always
    networks:
      - search-engine-example-network

  redis:
    image: redis:7.2-alpine
    command: redis-server
    container_name: search-engine-example-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - search-engine-example-network

networks:
  search-engine-example-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
